### ISSUE TITLE
Unable to load discord-rpc.asi. Error: 126

### ISSUE THREAD

**Issue by cyristm** [wictornogueira/nfsu2-rpc#1]
With the rpc mod & ThirteenAG's ASI loader installed. I always get the error above upon boot. This only happens when the rpc is installed. Other ASI scripts works fine

I'm using the HOODLUM v1.2 No-CD Crack (4,800,512 bytes)

**Comment by wictornogueira** [comment]
Interesting...
I've tested it using ThirteenAG's Ultimate ASI Loader and it works just fine.
Have you copied `discord-rpc.dll` to your game root dir?

**Comment by cyristm** [comment]
Yep. the rpc DLL is in my root dir

**Comment by wictornogueira** [comment]
🤔
What OS are you using?
Do you have all vc++ redistributables installed?

**Comment by wictornogueira** [comment]
Dumps/logs would also be welcome...

**Comment by cyristm** [comment]
w10 x64 home

I do have the VC++ redistributables installed (x64 & x86)

As for generating a log, I'm not sure how to do it with 13AG's asi loader. 
Since the game does boot as normal after pressing OK on the error, along with the other ASI scripts (widescreen, extra options, HD font, HD reflections, etc)

I have tried the rpc on a clean install of the game, but the same error appears

I'm using the latest release of the rpc

**Comment by wictornogueira** [comment]
Okay, I may have figured out what was wrong... Try this one
[discord-rpc.zip](https://github.com/wictornogueira/nfsu2-rpc/files/6463308/discord-rpc.zip)

**Comment by cyristm** [comment]
Yep. That one works flawlessly! Thank you!!

**Comment by wictornogueira** [comment]
You welcome :D
Btw, thank you for reporting this issue

**Comment by cyristm** [comment]
No problem! I also want to thank you for this neat RPC mod :D
